-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.authorities
(
    username character varying(100) COLLATE pg_catalog."default",
    authority character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT uk_username_authority UNIQUE (username, authority)
);

CREATE TABLE IF NOT EXISTS public.course
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    tutor_id integer,
    CONSTRAINT course_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customer
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(255) COLLATE pg_catalog."default",
    first_name character varying(255) COLLATE pg_catalog."default",
    last_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT customer_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.employee
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(255) COLLATE pg_catalog."default",
    first_name character varying(255) COLLATE pg_catalog."default",
    last_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT employee_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.instructor
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    instructor_detail_id integer,
    CONSTRAINT instructor_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.instructor_details
(
    id serial NOT NULL,
    hobby character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT instructor_details_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.members
(
    user_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    pw character varying(255) COLLATE pg_catalog."default" NOT NULL,
    active boolean NOT NULL,
    CONSTRAINT members_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.review
(
    id bigserial NOT NULL,
    comment text COLLATE pg_catalog."default",
    course_id bigint,
    CONSTRAINT review_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    user_id character varying(100) COLLATE pg_catalog."default",
    role character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT uk_user_id_role UNIQUE (user_id, role)
);

CREATE TABLE IF NOT EXISTS public.student
(
    id serial NOT NULL,
    first_name character varying(255) COLLATE pg_catalog."default",
    last_name character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT student_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.student_subject
(
    student_id bigint NOT NULL,
    subject_id bigint NOT NULL,
    CONSTRAINT student_subject_pkey PRIMARY KEY (student_id, subject_id)
);

CREATE TABLE IF NOT EXISTS public.subject
(
    id bigserial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT subject_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tutor
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tutor_pkey PRIMARY KEY (id),
    CONSTRAINT tutor_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.users
(
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    enabled boolean NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (username)
);

ALTER TABLE IF EXISTS public.authorities
    ADD CONSTRAINT fk_authorities_users FOREIGN KEY (username)
    REFERENCES public.users (username) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.course
    ADD CONSTRAINT fk_course_tutor FOREIGN KEY (tutor_id)
    REFERENCES public.tutor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.instructor
    ADD CONSTRAINT fk_instructor_detail FOREIGN KEY (instructor_detail_id)
    REFERENCES public.instructor_details (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.review
    ADD CONSTRAINT fk_review_course FOREIGN KEY (course_id)
    REFERENCES public.course (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.roles
    ADD CONSTRAINT fk_roles_members FOREIGN KEY (user_id)
    REFERENCES public.members (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.student_subject
    ADD CONSTRAINT fk_student FOREIGN KEY (student_id)
    REFERENCES public.student (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.student_subject
    ADD CONSTRAINT fk_subject FOREIGN KEY (subject_id)
    REFERENCES public.subject (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;